<?php
// Hướng dẫn backup & restore + tạo backup qua mysqldump (nếu có quyền admin)
requirePermission(AppPermission::MANAGE_CATALOG); // Manager+ mới xem
global $conn;

$msg = '';
$db_stats = [];

// Lấy thống kê DB
$tables = ['accounts','items','invoices','invoice_details','inventory_receipts','inventory_exports',
           'salary_records','leave_requests','resignation_requests','positions','customers','suppliers'];
foreach ($tables as $t) {
    $r = mysqli_query($conn, "SELECT COUNT(*) AS c FROM `$t`");
    $db_stats[$t] = $r ? (int)mysqli_fetch_assoc($r)['c'] : 0;
}

// Lấy DB size
$size_r = mysqli_query($conn, "SELECT ROUND(SUM(data_length + index_length)/1024, 2) AS size_kb
    FROM information_schema.tables WHERE table_schema = DATABASE()");
$db_size = $size_r ? (float)mysqli_fetch_assoc($size_r)['size_kb'] : 0;

// Lấy ngày tạo lần đầu (account đầu tiên)
$oldest_r = mysqli_query($conn, "SELECT MIN(created_at) AS oldest FROM accounts");
$oldest = $oldest_r ? mysqli_fetch_assoc($oldest_r)['oldest'] : null;

// Tạo export SQL đơn giản qua PHP (limited)
if (isset($_POST['quick_export'])) {
    header('Content-Type: application/sql; charset=utf-8');
    header('Content-Disposition: attachment; filename="eldercoffee_backup_' . date('Ymd_His') . '.sql"');
    echo "-- ElderCoffee Database Backup\n";
    echo "-- Date: " . date('Y-m-d H:i:s') . "\n";
    echo "-- Generated by: " . htmlspecialchars($_SESSION['full_name'] ?? 'System') . "\n\n";
    echo "SET NAMES utf8mb4;\nSET FOREIGN_KEY_CHECKS=0;\n\n";

    foreach ($tables as $t) {
        echo "-- Table: $t\n";
        echo "TRUNCATE TABLE `$t`;\n";
        $rows_r = mysqli_query($conn, "SELECT * FROM `$t`");
        if (!$rows_r || mysqli_num_rows($rows_r) === 0) { echo "\n"; continue; }
        while ($row = mysqli_fetch_assoc($rows_r)) {
            $vals = array_map(function($v) use ($conn) {
                if ($v === null) return 'NULL';
                return "'" . mysqli_real_escape_string($conn, $v) . "'";
            }, array_values($row));
            echo "INSERT INTO `$t` VALUES (" . implode(',', $vals) . ");\n";
        }
        echo "\n";
    }
    echo "SET FOREIGN_KEY_CHECKS=1;\n";
    exit;
}
?>

<div class="dash_board px-2">
    <h1 class="head-name">SAO LƯU & PHỤC HỒI DỮ LIỆU</h1>
    <div class="head-line"></div>

    <!-- Thống kê DB -->
    <div class="row g-3 mt-2 mb-3">
        <div class="col-md-3">
            <div class="card border-info shadow-sm text-center">
                <div class="card-body">
                    <div class="text-info"><i class="fa-solid fa-database fa-3x"></i></div>
                    <div class="fs-5 fw-bold mt-2"><?= number_format($db_size, 0) ?> KB</div>
                    <small>Dung lượng CSDL</small>
                </div>
            </div>
        </div>
        <div class="col-md-3">
            <div class="card border-success shadow-sm text-center">
                <div class="card-body">
                    <div class="text-success"><i class="fa-solid fa-table fa-3x"></i></div>
                    <div class="fs-5 fw-bold mt-2"><?= count($tables) ?> bảng</div>
                    <small>Tổng số bảng dữ liệu</small>
                </div>
            </div>
        </div>
        <div class="col-md-3">
            <div class="card text-center shadow-sm">
                <div class="card-body">
                    <div><i class="fa-solid fa-receipt fa-3x text-muted"></i></div>
                    <div class="fs-5 fw-bold mt-2"><?= number_format($db_stats['invoices']) ?> HĐ</div>
                    <small><?= number_format($db_stats['items']) ?> SP | <?= number_format($db_stats['accounts']) ?> TK</small>
                </div>
            </div>
        </div>
        <div class="col-md-3">
            <div class="card text-center shadow-sm">
                <div class="card-body">
                    <div><i class="fa-solid fa-clock fa-3x text-muted"></i></div>
                    <div class="fs-6 fw-bold mt-2"><?= $oldest ? date('d/m/Y', strtotime($oldest)) : 'N/A' ?></div>
                    <small>Dữ liệu từ</small>
                </div>
            </div>
        </div>
    </div>

    <div class="row g-3">
        <!-- Backup -->
        <div class="col-lg-6">
            <div class="card shadow-sm border-primary">
                <div class="card-header fw-bold bg-primary text-white">
                    <i class="fa-solid fa-cloud-arrow-down me-2"></i>SAO LƯU DỮ LIỆU (BACKUP)
                </div>
                <div class="card-body">
                    <h6 class="fw-bold">Phương án 1: Tải file SQL qua trình duyệt</h6>
                    <p class="text-muted small">Tạo file .sql chứa dữ liệu hiện tại của các bảng chính (không bao gồm cấu trúc bảng).</p>
                    <form method="POST" action="">
                        <button type="submit" name="quick_export" class="btn btn-primary fw-bold mb-3">
                            <i class="fa-solid fa-download me-2"></i>Tải file SQL backup ngay
                        </button>
                    </form>

                    <hr>
                    <h6 class="fw-bold">Phương án 2: phpMyAdmin (Khuyến nghị)</h6>
                    <div class="alert alert-light border">
                        <ol class="mb-0 small">
                            <li>Mở <a href="http://localhost/phpmyadmin" target="_blank" class="fw-bold">phpMyAdmin</a></li>
                            <li>Chọn database <code>eldercoffee_db</code></li>
                            <li>Click tab <b>Export</b></li>
                            <li>Chọn format: <b>SQL</b>, chọn <b>Quick</b></li>
                            <li>Click <b>Go</b> để tải file</li>
                            <li>Đặt tên file theo quy tắc: <code>backup_YYYYMMDD.sql</code></li>
                        </ol>
                    </div>

                    <hr>
                    <h6 class="fw-bold">Phương án 3: Command Line (mysqldump)</h6>
                    <div class="bg-dark text-success p-3 rounded small font-monospace">
                        <div>-- Di chuyển vào thư mục muốn lưu backup</div>
                        <div>cd C:\xampp\mysql\bin</div>
                        <div class="mt-2">-- Tạo backup đầy đủ</div>
                        <div>mysqldump -u root -p eldercoffee_db &gt; C:\backup\eldercoffee_<?= date('Ymd') ?>.sql</div>
                        <div class="mt-2">-- Backup chỉ schema (không có data)</div>
                        <div>mysqldump -u root -p --no-data eldercoffee_db &gt; schema_only.sql</div>
                    </div>
                </div>
            </div>
        </div>

        <!-- Restore -->
        <div class="col-lg-6">
            <div class="card shadow-sm border-warning">
                <div class="card-header fw-bold bg-warning text-dark">
                    <i class="fa-solid fa-cloud-arrow-up me-2"></i>PHỤC HỒI DỮ LIỆU (RESTORE)
                </div>
                <div class="card-body">
                    <div class="alert alert-danger">
                        <i class="fa-solid fa-triangle-exclamation me-2"></i>
                        <b>Cảnh báo: Restore sẽ GHI ĐÈ toàn bộ dữ liệu hiện tại!</b>
                        Hãy tạo backup mới trước khi restore.
                    </div>

                    <h6 class="fw-bold">Phương án 1: phpMyAdmin Import</h6>
                    <div class="alert alert-light border">
                        <ol class="mb-0 small">
                            <li>Mở <a href="http://localhost/phpmyadmin" target="_blank" class="fw-bold">phpMyAdmin</a></li>
                            <li>Chọn database <code>eldercoffee_db</code></li>
                            <li>Click tab <b>Import</b></li>
                            <li>Chọn <b>Choose File</b> → chọn file .sql backup</li>
                            <li>Click <b>Go</b> để restore</li>
                        </ol>
                    </div>

                    <hr>
                    <h6 class="fw-bold">Phương án 2: Command Line (mysql)</h6>
                    <div class="bg-dark text-success p-3 rounded small font-monospace">
                        <div>cd C:\xampp\mysql\bin</div>
                        <div class="mt-2">-- Restore từ file backup</div>
                        <div>mysql -u root -p eldercoffee_db &lt; backup_file.sql</div>
                        <div class="mt-2">-- Hoặc setup fresh từ schema file</div>
                        <div>mysql -u root -p -e "CREATE DATABASE IF NOT EXISTS eldercoffee_db CHARACTER SET utf8mb4"</div>
                        <div>mysql -u root -p eldercoffee_db &lt; eldercoffee_db.sql</div>
                    </div>

                    <hr>
                    <h6 class="fw-bold">Lịch sao lưu khuyến nghị</h6>
                    <ul class="small mb-0">
                        <li><b>Hàng ngày:</b> Backup tự động lúc 23:00 (cần cài Windows Task Scheduler)</li>
                        <li><b>Hàng tuần:</b> Backup đầy đủ vào thứ 2 đầu tuần</li>
                        <li><b>Trước mỗi update:</b> Luôn backup trước khi update code/DB</li>
                        <li><b>Lưu trữ:</b> Ít nhất 30 ngày backup cũ nhất</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>

    <!-- Bảng thống kê chi tiết -->
    <div class="card shadow-sm mt-3">
        <div class="card-header fw-bold"><i class="fa-solid fa-list me-2"></i>Thống Kê Số Bản Ghi Theo Bảng</div>
        <div class="card-body p-0">
            <div class="row g-0">
                <?php foreach ($db_stats as $table => $count): ?>
                <div class="col-6 col-md-4 col-lg-3 border-end border-bottom p-3">
                    <div class="d-flex justify-content-between align-items-center">
                        <span class="fw-bold text-muted small"><?= $table ?></span>
                        <span class="badge text-bg-<?= $count > 0 ? 'primary' : 'secondary' ?> fs-6"><?= number_format($count) ?></span>
                    </div>
                </div>
                <?php endforeach; ?>
            </div>
        </div>
    </div>
</div>
</div>
</div>
</div>
</div>
